/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luisb' at '03/11/16 16:56' with Gradle 3.1
 *
 * @author luisb, @date 03/11/16 16:56
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
